import { mount } from '@matthesketh/utopia-runtime'
import { createRouter } from '@matthesketh/utopia-router'
import App from './App.utopia'

// File-based routes are auto-generated by the vite plugin
import routes from 'virtual:utopia-routes'

createRouter(routes)
mount(App, '#app')
