import { createRouter } from '@matthesketh/utopia-router';
import { mount } from '@matthesketh/utopia-runtime';
// File-based routes are auto-generated by the vite plugin
import routes from 'virtual:utopia-routes';

import App from './App.utopia';

createRouter(routes);
mount(App, '#app');
